# Dependencies
markdown:         kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Yours Swiftly'
tagline:          'by Łukasz Kuczborski'
description:      'Blogged by <a href="https://twitter.com/lkuczborski" target="_blank">@lkuczborski</a>.'
url:              http://kuczborski.com
baseurl:          /
excerpt_separator: <!--more-->

author:
  name:           'Łukasz Kuczborski'
  url:            https://twitter.com/lkuczborski

paginate:         5

# Custom vars
github:           https://github.com/lkuczborski
twitter:          https://twitter.com/lkuczborski
allegro:          https://twitter.com/allegro_group
swift-warsaw:     https://twitter.com/swiftwarsaw

# Gems
gems: [jekyll-paginate]